// Objective-C API for talking to xraybridge Go package.
//   gobind -lang=objc xraybridge
//
// File is generated by gobind. Do not edit.

#ifndef __Xraybridge_H__
#define __Xraybridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class XraybridgeEngine;
@protocol XraybridgeMobileWriter;
@class XraybridgeMobileWriter;

@protocol XraybridgeMobileWriter <NSObject>
- (void)writePacket:(NSData* _Nullable)p0;
@end

@interface XraybridgeEngine : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

FOUNDATION_EXPORT void XraybridgeFeedPacket(NSData* _Nullable p0);

FOUNDATION_EXPORT BOOL XraybridgeStart(NSString* _Nullable configJSON, id<XraybridgeMobileWriter> _Nullable writer, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void XraybridgeStop(void);

@class XraybridgeMobileWriter;

@interface XraybridgeMobileWriter : NSObject <goSeqRefInterface, XraybridgeMobileWriter> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)writePacket:(NSData* _Nullable)p0;
@end

#endif
