
// Objective-C API for talking to the following Go packages
//
//	xraybridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __XrayBridge_FRAMEWORK_H__
#define __XrayBridge_FRAMEWORK_H__

#include "Xraybridge.objc.h"
#include "Universe.objc.h"

#endif
